### ISSUE TITLE
5.5 Portable release shows no updates?

### ISSUE THREAD

**Issue by Skrell** [Timthreetwelve/WUView#11]
#### Describe the bug: ####
- No updates are shown 

#### Windows Version and Build #: ####
- Windows 10 Home x64 19045.2965

#### Log File: ####

[WUView.20230520.log](https://github.com/Timthreetwelve/WUView/files/11523415/WUView.20230520.log)

#### Screenshots: ####
![image](https://github.com/Timthreetwelve/WUView/assets/590266/893e70ba-da0f-4a06-a6a5-35b55b6d21c3)

**Comment by Timthreetwelve** [comment]
If I'm understanding you correclty, you're asking why WUView isn't showing up in the list of installed programs. 

By [definition](https://portableapps.com/about/what_is_a_portable_app#definition), portable applications are not installed and therefore won't show up in the list of installed programs.

**Comment by Skrell** [comment]
No, I'm saying your app does nothing.  The portable release, at least, shows NO windows updates at all despite my OS having a bunch (see screenshot)

**Comment by Timthreetwelve** [comment]
I'm sorry. I misinterpreted your issue. The attached log shows that 4 update records were found. 

Could you try toggling the Excluded items and see if that shows anything? It's on the View menu or Ctrl+E.

**Comment by Skrell** [comment]
> I'm sorry. I misinterpreted your issue. The attached log shows that 4 update records were found.
> 
> Could you try toggling the Excluded items and see if that shows anything? It's on the View menu or Ctrl+E.

Tried it and it made no difference.  Is there a log file or something I can supply you with?

**Comment by Timthreetwelve** [comment]
I've just released 0.5.7. It doesn't contain anything that directly addresses your issue, but I did change one log message that may help point to a possible cause. Not very reassuring, I know. 

I keep going back to the log that you attached previously. It says that there were only four updates on that machine. That doesn't seem like enough unless Windows has recently been installed. 

If you are familiar with PowerShell and comfortable running commands from a stranger, could you execute the following? Note that it does **not** need to run as admin.

`$session = New-Object -ComObject Microsoft.Update.Session`
`$searcher = $session.CreateUpdateSearcher()`
`$historyCount = $searcher.GetTotalHistoryCount()`
`Write-Output "Found $historyCount updates"`

The code above will simply display the total update count.

Thanks for your help and your patience.

**Comment by Skrell** [comment]
![image](https://github.com/Timthreetwelve/WUView/assets/590266/84c903ca-1e48-439c-93b7-43554a660210)

**Comment by Skrell** [comment]
I don't understand this at all... how did it figure only 6?  If I go to control panel -> Installed Updates there are many more than 6!

**Comment by Timthreetwelve** [comment]
I'm at a loss to explain such a low number.  If you haven't already, look at the [wiki page](https://github.com/Timthreetwelve/WUView/wiki) and see if the second or third bullet points might apply.

I am curious to see what the 6 updates are. If you don't mind, would you run the PowerShell commands again and add `$Searcher.QueryHistory(0, $historyCount) | Select-Object Date, Title, ResultCode, Operation` to the end. The last line will list the updates that are found. Don't worry if the right side of the output is truncated. We're mostly interested in the date and the update title. The whole thing should look like this:

`$Session = New-Object -ComObject Microsoft.Update.Session`
`$Searcher = $Session.CreateUpdateSearcher()`
`$historyCount = $Searcher.GetTotalHistoryCount()`
`Write-Output "found $historyCount updates"`
`$Searcher.QueryHistory(0, $historyCount) | Select-Object Date, Title, ResultCode, Operation `

If you have installed 0.5.7 or later, could you attach the application log, please.

Finally, and I know this is asking a lot, could you download the NirSoft [Windows Update History Viewer]( https://www.nirsoft.net/utils/windows_updates_history_viewer.html) and see if its results are any different?

Thanks again for your patience and help. I realize that you aren't getting paid for your efforts, so the least that I can do is offer you my sincere thanks.

**Comment by Timthreetwelve** [comment]
It's been a month since your last comment. Have you been able to collect the information?

If the information in the wiki has explained the small number of updates, or if you don't want to pursue this any longer, let me know and I will close the issue.

**Comment by Skrell** [comment]
My apologies for not following up.   I'll try what you ask tomorrow and let you know the result.  Ty for reaching out again!

**Comment by Skrell** [comment]
I just looked at the wiki's 2nd and 3rd bullet points but honestly I've had this installation of Windows 10 for a couple of years so it's hard to say if either bullet directly applies.  However, I definitely never deleted anything in Windows\SoftwareDistibution
It is possible that at one point I did do a "windows update repair" so that's possibly the issue.  I'll see what nirsofts tool shows tomorrow as I've never had any issues with any of their tools before

**Comment by Skrell** [comment]
So I looked in nirsoft's Windows Update History Viewer and it also only sees a few updates... so I'm left to assume then that basically something got lost along the way for my Windows 10 system and this is the best I'll get for now:
![image](https://github.com/Timthreetwelve/WUView/assets/590266/fdf8427d-747f-46ee-a0bf-5a9f829c8270)

I guess we can close this ticket but it is frustrating that somehow Microsoft's own "Installed Updates" app can see all the way back in time; however, my guess is if I tried to uninstall any of the updates it would fail to find them at this point?
![image](https://github.com/Timthreetwelve/WUView/assets/590266/44ba0da2-a1b8-4163-8a48-d605d226692d)

**Comment by Timthreetwelve** [comment]
@Skrell, you are correct, it is frustrating. I don't necessarily think that anything is "lost" or that uninstalling them wouldn't work. Although I wouldn't do it just to prove a point.

What I am convinced of is that Microsoft uses a different method internally to track updates than the API they provide for us mortals to use. 

Thanks for taking your time to gather the screenshots and update the issue.

Tim
