### ISSUE TITLE
Please update to .NET 7

### ISSUE THREAD

**Issue by Scoty43** [Timthreetwelve/WUView#13]
### Brief summary of your request

Better use .NET 7 for future

### Request details

WUView need -NET 6 but the last is .NET 7.

**Comment by Timthreetwelve** [comment]
@Scoty43 Thanks for your interest in WUView. 😃 

Regarding .NET 7 and the future, .NET 6 is an LTS release and will be supported for 3 years, until November 2024. .NET 7 is an STS release and will only be supported for 18 months, until May 2024. [Source.](https://learn.microsoft.com/en-us/dotnet/core/releases-and-support)

The plan is to keep using .NET 6 until after the release of .NET 8, which will be an LTS release.
