### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by herz-ag** [Timthreetwelve/WUView#14]
### Brief summary of your request

column/tag for errors during installation 

### Request details

Hi Tim, you probably want to add a column to indicate errors during the installation process?

Thanks,
herz.AG

**Comment by Timthreetwelve** [comment]
@herz-ag Thanks for your interest in WUView and for opening this issue.

There's a Result column in the grid. It's the rightmost column, so maybe it wouldn't be visible if the window weren't big enough. The Result Code can also be found in the details pane. Both will indicate if there were errors.

If this wasn't what you were looking for, please provide additional details.

Thanks,
Tim

**Comment by herz-ag** [comment]
Hi Tim thanks for answering.
in fact I didnt see the result column. You want to move it before the title column.
When I move the column manually between date and title it goes back after switching to settings or about item.

FYI: When using the lower window cursor to make the window smaller no scrollbar comes up in the details frame, only when using the middle slider.

Thanks.
herz.AG

**Comment by Timthreetwelve** [comment]
@herz-ag Instead of moving the Result column for everyone, I added the code necessary to save the column order and restore it when starting the application. This enhancement will be included in the 0.5.12 update.

Thank you for the suggestion.
Tim

**Comment by herz-ag** [comment]
@Timthreetwelve  Thank you for your quick implementation! :-)

herz.AG
