### ISSUE TITLE
Bug Report:

### ISSUE THREAD

**Issue by ModelsRUs** [Timthreetwelve/WUView#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened or didn't happen

Only ~ 3 months of history shown. There are many updates shown in Windows > Settings> Windows Update > History that do not appear in app. Earliest update shown is 3/28/2023. They are NOT excluded with a filter

### Steps To Reproduce

closed and re-opened app. Ran again.

### Version

0.5.11.0

### Windows Version

Win 22H2 O/S Build 22621.1702

**Comment by ModelsRUs** [comment]
Actual updates date back to Dec 2022

**Comment by Timthreetwelve** [comment]
Good afternoon @ModelsRUs 

If you haven't already, please look at the Known Issues and Troubleshooting pages in the [Wiki](https://github.com/Timthreetwelve/WUView/wiki). Then attach the application log and the output from the PowerShell script.

Thanks,
Tim

**Comment by Timthreetwelve** [comment]
@ModelsRUs, If the information in the wiki has explained the small number of updates, or if you don't want to pursue this any longer, let me know and I will close the issue.

Thanks,
Tim
