### ISSUE TITLE
Bug Report:

### ISSUE THREAD

**Issue by ModelsRUs** [Timthreetwelve/WUView#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened or didn't happen

Sorry
Please see issue # 16 . Incorrectly marked as solved. Issue still exists. Thank you.

### Steps To Reproduce

See issue # 16

### Version

 0.5.11

### Windows Version

Win 22H2 build 22621.1848

### Relevant log output

```shell
See issue # 16
```

**Comment by Timthreetwelve** [comment]
I'm sorry that WUView isn't working for you. Perhaps the excellent NirSoft [Windows Updates History Viewer](https://www.nirsoft.net/utils/windows_updates_history_viewer.html) would serve your needs better.
