### ISSUE TITLE
Can you make WUView Portable?

### ISSUE THREAD

**Issue by pstein** [Timthreetwelve/WUView#2]
I would like to install WUView as a portable program (e.g. on an USB flash drive).

Can you make it portable?

Thank you

**Comment by Timthreetwelve** [comment]
When you say "portable program" what exactly are you asking for? Would it be as simple as having the files in a zip archive that could be copied to a USB drive?

**Comment by pstein** [comment]
Partially yes.

Additionally WUView should NOT write anything into registry or config files into C:\program files\ resp. C:\Program files (x86) or C:\users\ tree.

All files should be kept in installation directory or below in sub(sub) directories

**Comment by pstein** [comment]
No, .NET runtime need (should) not be included.
However WUView should check the presence of the required .NETs.

If not found a popup should appear:  ".NET v4.8 not found.Please install"

**Comment by Timthreetwelve** [comment]
I've included a zip archive that can be extracted to a USB drive in release 0.5.4. 

The .NET runtimes are not included. As for your suggestion, it's not possible for WUView itself to check for the presence of the required .NET runtime environment. However, .NET should take care of the situation and ask the user to install the proper runtime environment.

**Comment by pstein** [comment]
Works.
Thank you.

Just a hint:
You should offer a similar portable package for your other tools (like getMyIp and TimVer)

**Comment by pstein** [comment]
Works.
Thank you.

Just a hint:
You should offer a similar portable package for your other tools (like getMyIp and TimVer)
