### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by CrypticCus** [Timthreetwelve/WUView#23]
### Brief summary of your request

sOME FEATURES

### Request details

Can you add;

Hide/Show updates to prevent installation of some updates
Ability to opt in and out to insider updates / defender updates / driver updates
Disable/Enable windows updates/defender/microsoft store&updates

### Anything else?

thats all for now.

**Comment by Timthreetwelve** [comment]
@CrypticCus, thanks for the suggestions. Although they sound intriguing, I believe that they are not within the scope of an update history _viewer,_ and therefore not a good fit for this application.

Thanks,
Tim

**Comment by CrypticCus** [comment]
thank but with this minimal support it is useless. thank, ege.
