### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/WUView#24]
### Brief summary of your request

N/a hide

### Request details

Can you add a option to hide the n/a updates?

<img width="879" alt="2023-07-22_161116" src="https://github.com/Timthreetwelve/WUView/assets/48124325/c2270425-37a6-4486-8c2e-a107bd2c938f">

### Anything else?

Yes, sure! Bring me a cup of coffee! ;)

**Comment by Timthreetwelve** [comment]
@CMTriX, I've updated the exclude list logic to check the **KB Number** column as well as the **Title** column. Currently debating if this needs to be optional. I'll try to have a new release ready by the end of the day.

I think that if I brought you a coffee it would be undrinkable by the time it arrived. 🤢

**Comment by Timthreetwelve** [comment]
Sorry for leaving this open for so long.
