### ISSUE TITLE
Enhancement Request: Allow to show Update Log of Offline System

### ISSUE THREAD

**Issue by JustMyGithub** [Timthreetwelve/WUView#26]
### Brief summary of your request

Allow to show Update Log of offline system

### Request details

It would be great if it was possible to see the logs of a different system partition (not the one of the system it runs on) and see the log of that system without having to boot it up. 

### Anything else?

Either allow to point to the system drive ("use drive e:") or allow to import just the relevant artefacts/files (like x.log and y.evtx) - well, or both :)

**Comment by Timthreetwelve** [comment]
@JustMyGithub, I've investigated this, and I don't see a straightforward way to fulfill your request. 

WUView uses the Windows Update Agent API (WUApiLib.dll) to get the list of updates. From what I can tell, there isn't a way to point it to a specific file, drive, or machine. It just gets the updates from the machine that it's on.

I'll keep this in mind if I ever run across a way to do it.

Sorry to disappoint.

Tim

**Comment by JustMyGithub** [comment]
Thanks for checking. Too bad that it's not doable in straightforward fashion.
