### ISSUE TITLE
An error has occurred. Please see the logfile

### ISSUE THREAD

**Issue by mgeha** [Timthreetwelve/WUView#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues and have read the Known Issues and Troubleshooting topics in the Wiki

### What happened or didn't happen

After starting the program (v 0.5.16.0) I get a error message stating "An error has occurred. Please see the logfile". Then the application freezes and exits. There is no log file or I did not find it.

How can I help to resolve this problem?

### Version

0.5.16.0

### Windows Version

Win11 22H2 22621.1992

**Comment by mgeha** [comment]
Hi Tim,

i finally was able to genearte a log before the app crashed again. I attached it.

Regards
[WUView.20230805.log](https://github.com/Timthreetwelve/WUView/files/12266786/WUView.20230805.log)

**Comment by Timthreetwelve** [comment]
@mgeha, thanks to the log you supplied, I found the cause of the crash and implemented a fix. The fix will be included in 0.5.17. The cause was a null title in an update, which I didn't believe was possible. 

Thanks for your help,
Tim

**Comment by mgeha** [comment]
Hey Tim,
sorry to bother you again :-) I looks like it's still happening. But now I see the list of updates populated with a number of updates before the app crashes. In v. 0.5.16 the list was empty. I have attached a log for you.
My locale is DE_de, maybe something with german Umlauts? I am guessing, have no clue

Regards
[WUView.20230806.log](https://github.com/Timthreetwelve/WUView/files/12268813/WUView.20230806.log)

**Comment by Timthreetwelve** [comment]
@mgeha, I'm sorry this has taken so long. Real life got in the way. 

I've just released 0.5.19 which hopefully will fix your issue. I'm leaving this open pending confirmation from you that the bug is fixed.

Thanks for your patience.

Tim

**Comment by mgeha** [comment]
No worries Tim, I am happy to tell you that the issue has been fixed :-)

**Comment by Timthreetwelve** [comment]
@mgeha, reading this is a wonderful way to start the day. I'm glad that the issue is resolved.

Tim
