### ISSUE TITLE
Translation: Where is the file?

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/WUView#31]
### Report a problem with a translation

Where is the XML file to start language translation?

**Comment by Timthreetwelve** [comment]
@CMTriX I updated the Wiki page to have a link directly to the file. Please let me know if anything else isn't clear.

Thanks for keeping me on my toes.

**Comment by CMTriX** [comment]
THNX! DUTCH coming asap!

**Comment by Timthreetwelve** [comment]
When you say asap, you aren't joking.
