### ISSUE TITLE
Enhancement -  Enable multilanguage installer

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/WUView#38]
### Brief summary of your request

Add strings to have multilanguage installer

### Request details

@Timthreetwelve 

Please add in source code in a separate file (not in GUI file) the strings to make the instalelr multilanguage .

Thanks.

**Comment by Timthreetwelve** [comment]
WUView uses Inno Setup for the installer. Fortunately, a user named bovirus has already created an Italian translation. 😄 

My plan is for the next release to have a multilingual installer.

Thanks,
Tim

**Comment by bovirus** [comment]
@Timthreetwelve 

Is just a reminder to enable it.  ;-)
