### ISSUE TITLE
Enhancement - Set by default program to use Windows system language

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/WUView#39]
### Brief summary of your request

Modify installer to use System language

### Request details

@Timthreetwelve 

I installed the new version where is available my language (italian) but the installer leave unchanged the settings set by previous version (English).

Modify installer/configuration to use by default Windows system language.

For me is teh best settings.

Thanks.

**Comment by Timthreetwelve** [comment]
@bovirus, I've given this a lot of thought. The issue that you ran into is unique for the case where an existing version that didn't have the desired language was upgraded to a version that now has the desired language. Once the desired language is selected, the settings file is updated, and that language will be used going forward until it is changed again. This should only happen once. Please let me know if it reverts in a subsequent installation.

I could change the default of the UseOSLanguage setting to true and that would cause the app to use the current culture language _IF_ that language has been included in the app. However, this would only be useful for new installations, not updates. See the language selection logic in [App.xaml.cs.](https://github.com/Timthreetwelve/WUView/blob/main/WUView/App.xaml.cs) starting at line 37.

![WUView_2023-09-26_17-10-46](https://github.com/Timthreetwelve/WUView/assets/43152358/18293151-3c0e-43f1-a8c2-41dc597811a6)

The UseOSLanguage setting is the checkbox (in green). 

I hope this explains what is happening.

**Comment by bovirus** [comment]
@Timthreetwelve

I beleieve that enable automatic OS language/application language match (if availble) is a good option.

Of course is suful for each new installation.

**Comment by bovirus** [comment]
@Timthreetwelve 

Thanks.
