### ISSUE TITLE
Enhancemement Move EXIT button 

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/WUView#41]
### Brief summary of your request

Exit button

### Request details

Can you place the EXIT button on the bottom in the menu or make option for it?
In my case i often click EXIT by mistake

**Comment by Timthreetwelve** [comment]
I had a few minutes to look at this and while I can't easily move it to the bottom, I can hide it.

![2023-09-23_13-55-09](https://github.com/Timthreetwelve/WUView/assets/43152358/89c23402-b389-4f4b-9b98-b396ca2e821b)

**Comment by Timthreetwelve** [comment]
Would you provide a translation for: 
`<sys:String x:Key="SettingsItem_ShowExit">Show Exit in Navigation bar</sys:String>`

Thanks
Tim

**Comment by CMTriX** [comment]
<sys:String x:Key="SettingsItem_ShowExit">Toon optie 'afsluiten' in menu</sys:String>
