### ISSUE TITLE
Slovak Translation

### ISSUE THREAD

**Issue by Vaso73** [Timthreetwelve/WUView#59]
Slovak (sk-SK)

**Comment by Vaso73** [comment]
Im send Slovak Translation, please check it out...

[Strings.sk-SK.xaml.zip](https://github.com/Timthreetwelve/WUView/files/13243162/Strings.sk-SK.xaml.zip)

**Comment by Timthreetwelve** [comment]
@Vaso73 Would you tell me how to spell the name of the language, as it should appear in the language drop-down on the Settings page. This should be the local spelling of the language name. Microsoft says it's `slovenčina`, is that correct?

**Comment by Vaso73** [comment]
Yes, it is correct...

**Comment by Timthreetwelve** [comment]
Thank you! And thank you for contributing the translation!

**Comment by Vaso73** [comment]
You are WELCOME... :-)
