### ISSUE TITLE
Bug Report: - 0.5.25.0 - GUI issues

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/WUView#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues (both open and closed).

### What happened or didn't happen?

@Timthreetwelve 

Please check screnshots

![image](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/assets/1262554/bf3c2a29-0eeb-4624-83be-fd7e5965ff61)

On top right the item should be "Close menu" (Chiudi menu) and not like now 2Cancel" (Annulla)
On top left is what you are  naming "navigation bar2'
Becuae the command "Exit2 is different then command on top right

![image](https://github.com/Timthreetwelve/HWiNFO-VSB-Viewer/assets/1262554/60cfd2b4-59af-48fa-8e92-940b5e803017)

"ID" seems truncated
"Github" and "Contribute" seems not updated.

### Steps To Reproduce

Check screenshots

### Version

0.5.25.0

### Windows Version

Windows 10 22H2 64bit Italian

**Comment by Timthreetwelve** [comment]
@bovirus 

I've added new strings for About_GitHub and Button_Close. See 63e23d4.

It looks like the About_Contribute string in the it-IT file wasn't updated. I copied it from HWiNFOVSBViewer. Please check to see if it's correct. 

I'm not seeing any truncated fields. The column width is set to "auto" so it should expand to accommodate longer strings. Is the translated string correct? 

If you haven't seen it already, please look at https://github.com/Timthreetwelve/GetMyIP/issues/45#issuecomment-1807277233

**Comment by bovirus** [comment]
@Timthreetwelve 

You are right.

In translation should be "ID" commit" and instead I translated it as "IF commit":;
I will fix soon.

Please close the ticket.
