### ISSUE TITLE
Translation: nl-NL updates

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/WUView#64]
### Report a problem with a translation

@CMTriX 

When you have time, would you mind updating the nl-NL language file for Windows Update Viewer?

Since your last update I've had to change the procedure. Please refer to the [updated article](https://github.com/Timthreetwelve/WUView/wiki/Contribute-a-Translation#new-procedures-as-of-20231112) in the wiki.

There are just a few strings that need to be updated.
``` XML
<!-- Begin changes on 2023/11/13 @ 20:45 UTC -->
<!-- * | Value for About_Contribute needs to be updated to "Contribute a Translation" -->
<!-- * | The OperationType_* group needs to be translated -->
<!-- * | The ResultCode_* group needs to be translated -->
<!-- * | MenuItem_SaveJSON needs to be translated -->
<!-- * | SettingsItem_EnableLanguageTesting needs to be translated -->
<!-- A | About_GitHub needs to be added -->
<!-- A | Button_Close needs to be added -->
<!-- End of changes on 2023/11/13 -->
```
Thanks for your continued support! ❤️

Also, if you know anyone that could help with getting de-DE, fr-FR, or ca-ES, updated, or adding a language that is missing, ask them to join the fun. 😉

Tim

**Comment by comtronix** [comment]
ok,
- read 
-  download tool
- searching for the language file to update

**Comment by comtronix** [comment]
I think the translation update is done, please validate if you have time.

**Comment by CMTriX** [comment]
I deleted my comment. I was logged in old account. Sorry
