### ISSUE TITLE
New option request: refresh/update

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/WUView#9]
button to refresh the installed updates list.

**Comment by Timthreetwelve** [comment]
I'm working on it for the next release.

![2023-05-13_21-12-14](https://github.com/Timthreetwelve/WUView/assets/43152358/81e0442e-7287-42cb-94bf-e368a7b3cf47)

**Comment by CMTriX** [comment]
Amazing! Looks good!

**Comment by Timthreetwelve** [comment]
Implemented in 0.5.5.
